import Foundation

let appName = "321Doit"
let appAuthor = "毛鑫涛 / Mao Xintao"
// The running app's Info.plist is generated by build.sh, so it is the single
// source of truth for release metadata. Command-line smoke tests do not have an
// app bundle and therefore use the current internal-build values as
// deterministic fallbacks. Tools/check_internal_version.sh prevents these
// values from drifting away from build.sh.
let appVersionString = Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "0.7"
let appBuildNumberString = Bundle.main.object(forInfoDictionaryKey: "CFBundleVersion") as? String ?? "1"

/// Numeric macOS version with the build tag, language-neutral.
/// `ProcessInfo.operatingSystemVersionString` returns Apple's localized
/// "Version 15.3 (Build 24D60)" / "版本 15.3（版本 24D60）" form, which leaks
/// Chinese into English UI when the user's macOS UI language is Chinese.
func osVersionDisplay() -> String {
    let v = ProcessInfo.processInfo.operatingSystemVersion
    var version = "\(v.majorVersion).\(v.minorVersion)"
    if v.patchVersion != 0 {
        version += ".\(v.patchVersion)"
    }
    var size = 0
    sysctlbyname("kern.osversion", nil, &size, nil, 0)
    if size > 0 {
        var buffer = [CChar](repeating: 0, count: size)
        if sysctlbyname("kern.osversion", &buffer, &size, nil, 0) == 0 {
            let build = String(cString: buffer).trimmingCharacters(in: .whitespacesAndNewlines)
            if !build.isEmpty {
                return "\(version) (\(build))"
            }
        }
    }
    return version
}


// MARK: - Transcode profile

enum TranscodeCodec: String, CaseIterable, Equatable, Codable, Identifiable {
    case proresProxy
    case proresLT
    case prores422
    case prores422HQ
    case prores4444
    case prores4444XQ
    case h264
    case h265
    case h266

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .proresProxy:   return "ProRes 422 Proxy"
        case .proresLT:      return "ProRes 422 LT"
        case .prores422:     return "ProRes 422"
        case .prores422HQ:   return "ProRes 422 HQ"
        case .prores4444:    return "ProRes 4444"
        case .prores4444XQ:  return "ProRes 4444 XQ"
        case .h264:          return "H.264 / AVC"
        case .h265:          return "H.265 / HEVC"
        case .h266:          return "H.266 / VVC"
        }
    }

    var shortLabel: String {
        switch self {
        case .proresProxy:   return "PRX"
        case .proresLT:      return "LT"
        case .prores422:     return "422"
        case .prores422HQ:   return "HQ"
        case .prores4444:    return "4444"
        case .prores4444XQ:  return "XQ"
        case .h264:          return "H.264"
        case .h265:          return "HEVC"
        case .h266:          return "VVC"
        }
    }

    var family: String {
        switch self {
        case .proresProxy, .proresLT, .prores422, .prores422HQ, .prores4444, .prores4444XQ:
            return "Apple ProRes"
        case .h264:  return "H.264 (AVC)"
        case .h265:  return "H.265 (HEVC)"
        case .h266:  return "H.266 (VVC)"
        }
    }

    var isProRes: Bool {
        switch self {
        case .h264, .h265, .h266: return false
        default: return true
        }
    }

    var fileExtension: String {
        isProRes ? "mov" : "mp4"
    }

    var fileSuffix: String {
        switch self {
        case .proresProxy:   return "_proxy_prores"
        case .proresLT:      return "_proxy_prores_lt"
        case .prores422:     return "_proxy_prores_422"
        case .prores422HQ:   return "_proxy_prores_hq"
        case .prores4444:    return "_proxy_prores_4444"
        case .prores4444XQ:  return "_proxy_prores_xq"
        case .h264:          return "_proxy_h264"
        case .h265:          return "_proxy_h265"
        case .h266:          return "_proxy_h266"
        }
    }

    var folderName: String {
        switch self {
        case .proresProxy:   return "ProResProxy"
        case .proresLT:      return "ProResLT"
        case .prores422:     return "ProRes422"
        case .prores422HQ:   return "ProRes422HQ"
        case .prores4444:    return "ProRes4444"
        case .prores4444XQ:  return "ProRes4444XQ"
        case .h264:          return "H264"
        case .h265:          return "H265"
        case .h266:          return "H266"
        }
    }
}

enum TranscodeQuality: String, CaseIterable, Equatable, Codable, Identifiable {
    case low
    case medium
    case high

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .low:    return "Low"
        case .medium: return "Medium"
        case .high:   return "High"
        }
    }
}

enum TranscodeScale: String, CaseIterable, Equatable, Codable, Identifiable {
    case original
    case uhd2160
    case hd1080
    case hd720
    case half

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .original: return "Original"
        case .uhd2160:  return "UHD 3840 wide"
        case .hd1080:   return "FHD 1920 wide"
        case .hd720:    return "HD 1280 wide"
        case .half:     return "Half size"
        }
    }

    var ffmpegFilter: String? {
        switch self {
        case .original: return nil
        case .uhd2160:  return "scale=3840:-2"
        case .hd1080:   return "scale=1920:-2"
        case .hd720:    return "scale=1280:-2"
        case .half:     return "scale=iw/2:-2"
        }
    }
}

enum TranscodeBitrate: String, CaseIterable, Equatable, Codable, Identifiable {
    case auto
    case mbps5
    case mbps10
    case mbps25
    case mbps50
    case mbps100
    case mbps200
    case mbps400

    var id: String { rawValue }

    var mbps: Int? {
        switch self {
        case .auto:    return nil
        case .mbps5:   return 5
        case .mbps10:  return 10
        case .mbps25:  return 25
        case .mbps50:  return 50
        case .mbps100: return 100
        case .mbps200: return 200
        case .mbps400: return 400
        }
    }

    var displayName: String {
        switch self {
        case .auto: return "Auto (CRF)"
        case .mbps5,  .mbps10, .mbps25, .mbps50,
             .mbps100, .mbps200, .mbps400:
            return "\(mbps ?? 0) Mbps"
        }
    }
}

enum LUTMode: String, Codable, CaseIterable, Identifiable {
    case none
    case applyLUT
    case cleanAndLUT

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .none: return "None"
        case .applyLUT: return "Apply LUT"
        case .cleanAndLUT: return "Clean Proxy + LUT Proxy"
        }
    }
}

// MARK: - Burn-in

enum BurnInPosition: String, Codable, CaseIterable, Identifiable {
    case topLeft, topRight, bottomLeft, bottomRight, bottomCenter
    var id: String { rawValue }
    var label: (String, String) {
        switch self {
        case .topLeft:      return ("左上", "Top Left")
        case .topRight:     return ("右上", "Top Right")
        case .bottomLeft:   return ("左下", "Bottom Left")
        case .bottomRight:  return ("右下", "Bottom Right")
        case .bottomCenter: return ("底部居中", "Bottom Center")
        }
    }
}

enum BurnInSize: String, Codable, CaseIterable, Identifiable {
    case small, medium, large
    var id: String { rawValue }
    var label: (String, String) {
        switch self {
        case .small:  return ("小", "Small")
        case .medium: return ("中", "Medium")
        case .large:  return ("大", "Large")
        }
    }
}

struct BurnInFieldToggles: Codable, Equatable {
    var fileName: Bool = true
    var timecode: Bool = true
    var reelOrCard: Bool = true
    var cameraID: Bool = false
    var clipName: Bool = false
    var resolution: Bool = false
    var frameRate: Bool = false
    var lutName: Bool = false
    var projectName: Bool = false
    var shootDay: Bool = false
}

struct BurnInSettings: Codable, Equatable {
    var enabled: Bool = false
    var fields: BurnInFieldToggles = .init()
    var position: BurnInPosition = .bottomLeft
    var size: BurnInSize = .medium
    var target: BurnInTarget = .proxyTranscode

    init() {}

    private enum CodingKeys: String, CodingKey {
        case enabled, fields, position, size, target
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        enabled = try c.decodeIfPresent(Bool.self, forKey: .enabled) ?? false
        fields = try c.decodeIfPresent(BurnInFieldToggles.self, forKey: .fields) ?? .init()
        position = try c.decodeIfPresent(BurnInPosition.self, forKey: .position) ?? .bottomLeft
        size = try c.decodeIfPresent(BurnInSize.self, forKey: .size) ?? .medium
        target = try c.decodeIfPresent(BurnInTarget.self, forKey: .target) ?? .proxyTranscode
    }
}

enum BurnInTarget: String, Codable, CaseIterable, Identifiable {
    case proxyTranscode
    case reviewCopy

    var id: String { rawValue }

    var label: (String, String) {
        switch self {
        case .proxyTranscode:
            return ("代理 / 转码文件", "Proxy / Transcode")
        case .reviewCopy:
            return ("额外烧录审看副本", "Extra Burn-in Review Copy")
        }
    }
}

// MARK: - Frame Extraction

struct FrameExtractionSettings: Codable, Equatable {
    var enabled: Bool = false
    var framesPerVideo: Int = 3
    var embedInPDF: Bool = true
    var applyLUT: Bool = true
}

// MARK: - Checksum
// `ChecksumAlgorithm`, `XXHash64Implementation`, and `formatHash` now live in
// ChecksumTypes.swift so they can be shared by every 321Doit tool.

struct TranscodeProfile: Equatable, Codable {
    var codec: TranscodeCodec
    var quality: TranscodeQuality
    var bitrate: TranscodeBitrate
    var scale: TranscodeScale
    var attemptRaw: Bool
    var enableHardwareAcceleration: Bool = true
    var ffmpegPath: String? = nil
    
    var lutMode: LUTMode = .none
    /// Path to a .cube / .3dl LUT file.
    var lutPath: String? = nil
    /// 0...1 — interpolation between source (0) and full LUT (1).
    var lutIntensity: Double = 1.0

    var burnIn: BurnInSettings = .init()
    var frameExtraction: FrameExtractionSettings = .init()

    static let `default` = TranscodeProfile(
        codec: .proresProxy,
        quality: .medium,
        bitrate: .auto,
        scale: .hd1080,
        attemptRaw: false,
        enableHardwareAcceleration: true,
        ffmpegPath: nil,
        lutMode: .none,
        lutPath: nil,
        lutIntensity: 1.0,
        burnIn: .init()
    )

    var summary: String {
        var parts = [codec.displayName]
        if !codec.isProRes {
            if bitrate == .auto {
                parts.append(quality.displayName)
            } else {
                parts.append(bitrate.displayName)
            }
        }
        parts.append(scale.displayName)
        return parts.joined(separator: " · ")
    }
}

enum ProjectAssociationMode: String, Codable, Equatable {
    case independent
    case linkedProject
}

struct OffloadSettings: Codable, Equatable {
    var taskID: UUID = UUID()
    var projectAssociationMode: ProjectAssociationMode = .independent
    var linkedProjectID: UUID?
    var projectName: String
    var cardNumber: String
    var operatorName: String
    var camera: String
    var location: String
    var notes: String
    var sourceURL: URL
    var targetRoots: [URL]
    var createdAt: Date
    var generateProxies: Bool
    var transcodeProfile: TranscodeProfile = .default
    var language: AppLanguage = .system
    var checksumAlgorithm: ChecksumAlgorithm = .xxhash64
    var xxHash64Implementation: XXHash64Implementation = .automatic
    var copyBufferKB: Int = 1024
    var writeSidecarChecksum: Bool = true
    var generateAscMHL: Bool = true
    var generateCSVLog: Bool = true
    var generateJSONLog: Bool = true
    var generateTXTBrief: Bool = true
    var recordEnvironmentInReport: Bool = true
    var sourceCardProfile: CameraCardProfile = .unknown
    var verifyOnly: Bool = false
    var checksumRetryCount: Int = 0
    var enableSpeedLimit: Bool = false
    var speedLimitMBps: Int = 200
    var resumedFromJournal: Bool = false
    var strictResume: Bool = true
    var ioRetryCount: Int = 3
    /// Snapshot of post-handoff settings at job start (decoupled from live preferences).
    var handoff: HandoffSettings = .init()
    /// One job can write one or more package layouts. If more than one is
    /// selected, sibling output folders receive stable suffixes.
    var outputPackageModes: [OffloadPackageMode] = [.safeCopy]

    init(
        projectName: String,
        cardNumber: String,
        operatorName: String,
        camera: String,
        location: String,
        notes: String,
        sourceURL: URL,
        targetRoots: [URL],
        createdAt: Date,
        generateProxies: Bool,
        transcodeProfile: TranscodeProfile = .default,
        language: AppLanguage = .system,
        checksumAlgorithm: ChecksumAlgorithm = .xxhash64,
        xxHash64Implementation: XXHash64Implementation = .automatic,
        copyBufferKB: Int = 1024,
        writeSidecarChecksum: Bool = true,
        generateAscMHL: Bool = true,
        generateCSVLog: Bool = true,
        generateJSONLog: Bool = true,
        generateTXTBrief: Bool = true,
        recordEnvironmentInReport: Bool = true,
        sourceCardProfile: CameraCardProfile = .unknown,
        verifyOnly: Bool = false,
        checksumRetryCount: Int = 0,
        enableSpeedLimit: Bool = false,
        speedLimitMBps: Int = 200,
        resumedFromJournal: Bool = false,
        strictResume: Bool = true,
        ioRetryCount: Int = 3,
        handoff: HandoffSettings = .init(),
        outputPackageModes: [OffloadPackageMode] = [.safeCopy],
        taskID: UUID = UUID(),
        projectAssociationMode: ProjectAssociationMode = .independent,
        linkedProjectID: UUID? = nil
    ) {
        self.taskID = taskID
        self.projectAssociationMode = projectAssociationMode
        self.linkedProjectID = linkedProjectID
        self.projectName = projectName
        self.cardNumber = cardNumber
        self.operatorName = operatorName
        self.camera = camera
        self.location = location
        self.notes = notes
        self.sourceURL = sourceURL
        self.targetRoots = targetRoots
        self.createdAt = createdAt
        self.generateProxies = generateProxies
        self.transcodeProfile = transcodeProfile
        self.language = language
        self.checksumAlgorithm = checksumAlgorithm
        self.xxHash64Implementation = xxHash64Implementation
        self.copyBufferKB = copyBufferKB
        self.writeSidecarChecksum = writeSidecarChecksum
        self.generateAscMHL = generateAscMHL
        self.generateCSVLog = generateCSVLog
        self.generateJSONLog = generateJSONLog
        self.generateTXTBrief = generateTXTBrief
        self.recordEnvironmentInReport = recordEnvironmentInReport
        self.sourceCardProfile = sourceCardProfile
        self.verifyOnly = verifyOnly
        self.checksumRetryCount = checksumRetryCount
        self.enableSpeedLimit = enableSpeedLimit
        self.speedLimitMBps = speedLimitMBps
        self.resumedFromJournal = resumedFromJournal
        self.strictResume = strictResume
        self.ioRetryCount = ioRetryCount
        self.handoff = handoff
        self.outputPackageModes = outputPackageModes
    }

    var outputFolderName: String {
        makeOutputFolderName(project: projectName, date: createdAt, card: cardNumber)
    }

    var normalizedOutputPackageModes: [OffloadPackageMode] {
        var seen = Set<OffloadPackageMode>()
        let ordered = outputPackageModes.filter { seen.insert($0).inserted }
        return ordered.isEmpty ? [.safeCopy] : ordered
    }

    func outputFolderName(for mode: OffloadPackageMode) -> String {
        if normalizedOutputPackageModes.count == 1 {
            return outputFolderName
        }
        return "\(outputFolderName)_\(mode.folderSuffix)"
    }
}

extension OffloadSettings {
    private enum CodingKeys: String, CodingKey {
        case taskID
        case projectAssociationMode
        case linkedProjectID
        case projectName
        case cardNumber
        case operatorName
        case camera
        case location
        case notes
        case sourceURL
        case targetRoots
        case createdAt
        case generateProxies
        case transcodeProfile
        case language
        case checksumAlgorithm
        case xxHash64Implementation
        case copyBufferKB
        case writeSidecarChecksum
        case generateAscMHL
        case generateCSVLog
        case generateJSONLog
        case generateTXTBrief
        case recordEnvironmentInReport
        case sourceCardProfile
        case verifyOnly
        case checksumRetryCount
        case enableSpeedLimit
        case speedLimitMBps
        case resumedFromJournal
        case strictResume
        case ioRetryCount
        case handoff
        case outputPackageModes
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        taskID = try container.decodeIfPresent(UUID.self, forKey: .taskID) ?? UUID()
        projectAssociationMode = try container.decodeIfPresent(ProjectAssociationMode.self, forKey: .projectAssociationMode) ?? .independent
        linkedProjectID = try container.decodeIfPresent(UUID.self, forKey: .linkedProjectID)
        projectName = try container.decode(String.self, forKey: .projectName)
        cardNumber = try container.decode(String.self, forKey: .cardNumber)
        operatorName = try container.decode(String.self, forKey: .operatorName)
        camera = try container.decodeIfPresent(String.self, forKey: .camera) ?? ""
        location = try container.decodeIfPresent(String.self, forKey: .location) ?? ""
        notes = try container.decodeIfPresent(String.self, forKey: .notes) ?? ""
        sourceURL = try container.decode(URL.self, forKey: .sourceURL)
        targetRoots = try container.decode([URL].self, forKey: .targetRoots)
        createdAt = try container.decodeIfPresent(Date.self, forKey: .createdAt) ?? Date()
        generateProxies = try container.decodeIfPresent(Bool.self, forKey: .generateProxies) ?? false
        transcodeProfile = try container.decodeIfPresent(TranscodeProfile.self, forKey: .transcodeProfile) ?? .default
        language = try container.decodeIfPresent(AppLanguage.self, forKey: .language) ?? .system
        checksumAlgorithm = try container.decodeIfPresent(ChecksumAlgorithm.self, forKey: .checksumAlgorithm) ?? .xxhash64
        xxHash64Implementation = try container.decodeIfPresent(XXHash64Implementation.self, forKey: .xxHash64Implementation) ?? .automatic
        copyBufferKB = try container.decodeIfPresent(Int.self, forKey: .copyBufferKB) ?? 1024
        writeSidecarChecksum = try container.decodeIfPresent(Bool.self, forKey: .writeSidecarChecksum) ?? true
        generateAscMHL = try container.decodeIfPresent(Bool.self, forKey: .generateAscMHL) ?? true
        generateCSVLog = try container.decodeIfPresent(Bool.self, forKey: .generateCSVLog) ?? true
        generateJSONLog = try container.decodeIfPresent(Bool.self, forKey: .generateJSONLog) ?? true
        generateTXTBrief = try container.decodeIfPresent(Bool.self, forKey: .generateTXTBrief) ?? true
        recordEnvironmentInReport = try container.decodeIfPresent(Bool.self, forKey: .recordEnvironmentInReport) ?? true
        sourceCardProfile = try container.decodeIfPresent(CameraCardProfile.self, forKey: .sourceCardProfile) ?? .unknown
        verifyOnly = try container.decodeIfPresent(Bool.self, forKey: .verifyOnly) ?? false
        checksumRetryCount = try container.decodeIfPresent(Int.self, forKey: .checksumRetryCount) ?? 0
        enableSpeedLimit = try container.decodeIfPresent(Bool.self, forKey: .enableSpeedLimit) ?? false
        speedLimitMBps = try container.decodeIfPresent(Int.self, forKey: .speedLimitMBps) ?? 200
        resumedFromJournal = try container.decodeIfPresent(Bool.self, forKey: .resumedFromJournal) ?? false
        strictResume = try container.decodeIfPresent(Bool.self, forKey: .strictResume) ?? true
        ioRetryCount = try container.decodeIfPresent(Int.self, forKey: .ioRetryCount) ?? 3
        handoff = try container.decodeIfPresent(HandoffSettings.self, forKey: .handoff) ?? .init()
        outputPackageModes = try container.decodeIfPresent([OffloadPackageMode].self, forKey: .outputPackageModes) ?? [.safeCopy]
    }
}

enum OffloadPackageMode: String, Codable, CaseIterable, Identifiable, Hashable {
    case safeCopy
    case editorialDelivery

    var id: String { rawValue }

    var label: (String, String) {
        switch self {
        case .safeCopy:
            return ("标准安全拷卡", "Safe Copy")
        case .editorialDelivery:
            return ("剪辑交付包", "Editorial Delivery")
        }
    }

    var folderSuffix: String {
        switch self {
        case .safeCopy: return "SAFE"
        case .editorialDelivery: return "EDIT"
        }
    }
}

enum ProxyOutputKind {
    case standard
    case lutBaked
    case clean
    case burnIn
}

enum OffloadPackageLayout {
    static func isLegacyLayout(outputURL: URL) -> Bool {
        let fm = FileManager.default
        return fm.fileExists(atPath: outputURL.appendingPathComponent("01_ORIGINALS").path)
            || fm.fileExists(atPath: outputURL.appendingPathComponent("_321Doit/session.json").path)
    }

    static func originalsRoot(outputURL: URL, mode: OffloadPackageMode, cardNumber: String) -> URL {
        let root = outputURL.appendingPathComponent(
            isLegacyLayout(outputURL: outputURL) ? "01_ORIGINALS" : "MEDIA",
            isDirectory: true
        )
        switch mode {
        case .safeCopy:
            let card = sanitizedComponent(cardNumber, fallback: "CARD001")
            return root.appendingPathComponent(card, isDirectory: true)
        case .editorialDelivery:
            return root
        }
    }

    static func originalFileURL(outputURL: URL, mode: OffloadPackageMode, cardNumber: String, relativePath: String) -> URL {
        originalsRoot(outputURL: outputURL, mode: mode, cardNumber: cardNumber)
            .appendingPathComponent(relativePath)
    }

    static func reportsRoot(outputURL: URL) -> URL {
        outputURL.appendingPathComponent(
            isLegacyLayout(outputURL: outputURL) ? "03_REPORTS" : "REPORTS",
            isDirectory: true
        )
    }

    static func checksumsRoot(outputURL: URL, mode: OffloadPackageMode) -> URL {
        switch mode {
        case .safeCopy:
            return outputURL.appendingPathComponent(
                isLegacyLayout(outputURL: outputURL) ? "04_CHECKSUMS" : "CHECKSUMS",
                isDirectory: true
            )
        case .editorialDelivery:
            return reportsRoot(outputURL: outputURL)
        }
    }

    static func proxiesRoot(outputURL: URL) -> URL {
        outputURL.appendingPathComponent(
            isLegacyLayout(outputURL: outputURL) ? "02_PROXIES" : "PROXIES",
            isDirectory: true
        )
    }

    static func proxyRoot(outputURL: URL, profile: TranscodeProfile, kind: ProxyOutputKind) -> URL {
        let root = proxiesRoot(outputURL: outputURL)
        switch kind {
        case .standard:
            return root.appendingPathComponent(profile.codec.folderName, isDirectory: true)
        case .lutBaked:
            return root.appendingPathComponent("LUT_Baked", isDirectory: true)
        case .clean:
            return root.appendingPathComponent("Clean", isDirectory: true)
        case .burnIn:
            return root.appendingPathComponent("BurnIn", isDirectory: true)
        }
    }

    static func thumbnailsRoot(outputURL: URL) -> URL {
        outputURL.appendingPathComponent(
            isLegacyLayout(outputURL: outputURL) ? "06_THUMBNAILS" : "THUMBNAILS",
            isDirectory: true
        )
    }

    static func handoffRoot(outputURL: URL) -> URL {
        outputURL.appendingPathComponent(
            isLegacyLayout(outputURL: outputURL) ? "05_HANDOFF" : "INTEGRATIONS",
            isDirectory: true
        )
    }

    static func workflowRoot(outputURL: URL) -> URL {
        outputURL.appendingPathComponent(
            isLegacyLayout(outputURL: outputURL) ? "_321Doit" : ".321doit",
            isDirectory: true
        )
    }

    static func ascMHLRoot(outputURL: URL, mode: OffloadPackageMode, cardNumber: String) -> URL {
        if isLegacyLayout(outputURL: outputURL) {
            return outputURL.appendingPathComponent("ascmhl", isDirectory: true)
        }
        return originalsRoot(outputURL: outputURL, mode: mode, cardNumber: cardNumber)
            .appendingPathComponent("ascmhl", isDirectory: true)
    }

    static func targetRelativePath(outputURL: URL, fileURL: URL) -> String {
        relativePath(from: outputURL, to: fileURL)
    }
}

enum PreflightSeverity: String, Equatable {
    case ok
    case warning
    case error
}

struct PreflightCheckResult: Identifiable, Equatable {
    let id = UUID()
    var severity: PreflightSeverity
    var message: String
    var detail: String?
}

struct MountedSourceCandidate: Identifiable, Equatable {
    let id = UUID()
    var volumeName: String
    var url: URL
    var profile: CameraCardProfile
    var videoFileCount: Int
    var status: String
    var suggestedCardName: String?
}

struct SourceFile: Identifiable, Equatable {
    let id = UUID()
    let url: URL
    let relativePath: String
    let size: UInt64
    let modifiedAt: Date
}

enum TargetState: String, Equatable {
    case pending = "Pending"
    case copying = "Copying"
    case verifying = "Verifying"
    case transcoding = "Transcoding"
    case completed = "Completed"
    case failed = "Failed"
}

struct TargetProgress: Identifiable, Equatable {
    let id: UUID
    let rootURL: URL
    let outputURL: URL
    var packageMode: OffloadPackageMode
    var state: TargetState
    var copiedBytes: UInt64
    var verifiedBytes: UInt64
    var transcodeProgress: Double?
    var error: String?
    var bytesPerSecond: Double = 0

    var displayName: String {
        let rootName = rootURL.lastPathComponent.isEmpty ? rootURL.path : rootURL.lastPathComponent
        return "\(rootName) · \(packageMode.folderSuffix)"
    }
}

struct FileTargetResult: Equatable {
    var rootPath: String
    var outputPath: String
    var copied: Bool
    var verified: Bool
    var hash: String?
    var error: String?
}

struct FileCopyRecord: Identifiable, Equatable {
    let id = UUID()
    var relativePath: String
    var size: UInt64
    var modifiedAt: Date
    var sourceHash: String
    var targetResults: [FileTargetResult]
}

struct OffloadSnapshot: Equatable {
    var message: String
    var totalFiles: Int
    var completedFiles: Int
    var totalBytes: UInt64
    var copiedBytes: UInt64
    var startedAt: Date?
    var targets: [TargetProgress]
    var recentLog: String?
    var averageBytesPerSecond: Double = 0
    var currentBytesPerSecond: Double = 0
    var etaSeconds: TimeInterval?

    var progress: Double {
        guard totalBytes > 0 else { return 0 }
        return min(1, Double(copiedBytes) / Double(totalBytes))
    }
}

struct TargetReport: Equatable {
    var rootURL: URL
    var outputURL: URL
    var packageMode: OffloadPackageMode
    var state: TargetState
    var copiedBytes: UInt64
    var verifiedBytes: UInt64
    var error: String?
    var mhlURL: URL?
    var pdfURL: URL?
    var csvURL: URL?
    var jsonURL: URL?
    var txtURL: URL?
    var sidecarURL: URL?
    var proxyURL: URL?
    var proxyFilesCreated: Int
    var proxyErrors: [String]
    var handoff: HandoffOutput? = nil
}

/// Where 321Doit wrote post-handoff packages for one target.
struct HandoffOutput: Equatable {
    var rootURL: URL                 // 05_HANDOFF dir
    var manifestURL: URL?
    var resolveScriptURL: URL?       // resolve_import.py
    var resolveJSONURL: URL?         // resolve_import.json
    var fcpxmldURL: URL?             // PROJECT.fcpxmld
    var fcpxmlCompatURL: URL?        // PROJECT_compat.fcpxml
    var warnings: [String] = []
}

struct OffloadReport: Equatable {
    var settings: OffloadSettings
    var startedAt: Date
    var endedAt: Date
    var totalFiles: Int
    var totalBytes: UInt64
    var files: [FileCopyRecord]
    var targets: [TargetReport]
    var logs: [String]

    var successfulTargets: [TargetReport] {
        targets.filter { $0.state == .completed }
    }
}

enum OffloadError: LocalizedError {
    case missingRequiredFields
    case sourceUnavailable
    case noTargets
    case tooManyTargets
    case noFiles
    case duplicateTarget(URL)
    case duplicateOutput(URL)
    case nestedPath(String)
    case unsafeSourceLink(String)
    case insufficientSpace(target: URL, needed: UInt64, available: UInt64)
    case fat32LargeFile(target: URL, file: String, size: UInt64)
    case reportGenerationFailed([String])
    case allTargetsFailed

    var errorDescription: String? {
        switch self {
        case .missingRequiredFields:
            return "Project, card, operator, source and destination are all required."
        case .sourceUnavailable:
            return "Source does not exist or is not a folder."
        case .noTargets:
            return "Select at least one destination."
        case .tooManyTargets:
            return "This version supports at most 3 destinations."
        case .noFiles:
            return "No files to copy in the source."
        case .duplicateTarget(let url):
            return "Destination listed twice: \(url.path)"
        case .duplicateOutput(let url):
            return "Destination already has a folder with this card name; refused to overwrite: \(url.path)"
        case .nestedPath(let message):
            return message
        case .unsafeSourceLink(let path):
            return "Source contains a symbolic link or a path outside the selected source folder: \(path)"
        case .insufficientSpace(let target, let needed, let available):
            return "\(target.path) does not have enough free space; needs \(formatBytes(needed)), available \(formatBytes(available))."
        case .fat32LargeFile(let target, let file, let size):
            return "\(target.path) looks like FAT32 and cannot hold a single file larger than 4GB: \(file) (\(formatBytes(size))). Use exFAT or APFS instead."
        case .reportGenerationFailed(let messages):
            return "Media was copied, but one or more destination reports failed: \(messages.joined(separator: "; "))"
        case .allTargetsFailed:
            return "All destinations failed; the task did not complete."
        }
    }
}

let macJunkExact: Set<String> = [
    ".DS_Store",
    ".AppleDouble",
    ".LSOverride",
    ".Spotlight-V100",
    ".TemporaryItems",
    ".Trashes",
    ".fseventsd",
    ".DocumentRevisions-V100",
    ".VolumeIcon.icns",
    ".apdisk",
    ".localized",
    "__MACOSX",
    "Icon\r"
]

func isMacJunk(_ name: String) -> Bool {
    macJunkExact.contains(name) || name.hasPrefix("._")
}

func sanitizedComponent(_ value: String, fallback: String) -> String {
    let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
    let replaced = trimmed.unicodeScalars.map { scalar -> Character in
        if CharacterSet.alphanumerics.contains(scalar) || scalar == "_" || scalar == "-" {
            return Character(scalar)
        }
        return "_"
    }
    let compact = String(replaced)
        .replacingOccurrences(of: "__+", with: "_", options: .regularExpression)
        .trimmingCharacters(in: CharacterSet(charactersIn: "_-"))
    return compact.isEmpty ? fallback : compact.uppercased()
}

/// RFC 4180-style CSV escaping plus spreadsheet formula neutralization.
/// Project names, notes, and card file names are untrusted input; Excel and
/// Numbers interpret cells beginning with these characters as formulas.
func spreadsheetSafeCSVField(_ value: String, alwaysQuote: Bool = false) -> String {
    var safe = value
    if let first = safe.first, "=+-@\t\r".contains(first) {
        safe = "'" + safe
    }
    let escaped = safe.replacingOccurrences(of: "\"", with: "\"\"")
    if alwaysQuote || escaped.contains(",") || escaped.contains("\n") || escaped.contains("\"") {
        return "\"\(escaped)\""
    }
    return escaped
}

func makeOutputFolderName(project: String, date: Date, card: String) -> String {
    let projectPart = sanitizedComponent(project, fallback: "PROJECT")
    let cardPart = sanitizedComponent(card, fallback: "CARD")
    return "\(projectPart)_\(AppDateFormatters.outputFolderString(date))_\(cardPart)"
}

func formatBytes(_ bytes: UInt64) -> String {
    let units = ["B", "KB", "MB", "GB", "TB", "PB"]
    var value = Double(bytes)
    var index = 0
    while value >= 1024 && index < units.count - 1 {
        value /= 1024
        index += 1
    }
    if index == 0 || value >= 10 {
        return "\(Int(value.rounded())) \(units[index])"
    }
    return String(format: "%.1f %@", value, units[index])
}

func escapeXML(_ value: String) -> String {
    value
        .replacingOccurrences(of: "&", with: "&amp;")
        .replacingOccurrences(of: "<", with: "&lt;")
        .replacingOccurrences(of: ">", with: "&gt;")
        .replacingOccurrences(of: "\"", with: "&quot;")
        .replacingOccurrences(of: "'", with: "&apos;")
}

func iso8601String(_ date: Date) -> String {
    AppDateFormatters.iso8601String(date)
}

private enum AppDateFormatters {
    private static let outputFolderLock = NSLock()
    private static let outputFolderFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.calendar = Calendar(identifier: .gregorian)
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyyMMdd"
        return formatter
    }()

    private static let isoLock = NSLock()
    private static let isoFormatter: ISO8601DateFormatter = {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return formatter
    }()

    static func outputFolderString(_ date: Date) -> String {
        outputFolderLock.lock()
        defer { outputFolderLock.unlock() }
        return outputFolderFormatter.string(from: date)
    }

    static func iso8601String(_ date: Date) -> String {
        isoLock.lock()
        defer { isoLock.unlock() }
        return isoFormatter.string(from: date)
    }
}

func enumerateSourceFiles(at sourceURL: URL) throws -> [SourceFile] {
    let fileManager = FileManager.default
    var isDirectory: ObjCBool = false
    guard fileManager.fileExists(atPath: sourceURL.path, isDirectory: &isDirectory), isDirectory.boolValue else {
        throw OffloadError.sourceUnavailable
    }

    let keys: Set<URLResourceKey> = [
        .isDirectoryKey,
        .isRegularFileKey,
        .isSymbolicLinkKey,
        .fileSizeKey,
        .contentModificationDateKey
    ]
    guard let enumerator = fileManager.enumerator(
        at: sourceURL,
        includingPropertiesForKeys: Array(keys),
        options: [.skipsPackageDescendants]
    ) else {
        throw OffloadError.sourceUnavailable
    }

    var files: [SourceFile] = []
    let resolvedRoot = sourceURL.resolvingSymlinksInPath().standardizedFileURL
    for case let fileURL as URL in enumerator {
        let values = try fileURL.resourceValues(forKeys: keys)
        if values.isSymbolicLink == true {
            throw OffloadError.unsafeSourceLink(relativePath(from: sourceURL, to: fileURL))
        }
        if isMacJunk(fileURL.lastPathComponent) {
            if values.isDirectory == true {
                enumerator.skipDescendants()
            }
            continue
        }

        if values.isDirectory == true {
            continue
        }
        guard values.isRegularFile == true else {
            continue
        }

        let resolvedFile = fileURL.resolvingSymlinksInPath().standardizedFileURL
        guard isSameOrNested(resolvedFile, under: resolvedRoot) else {
            throw OffloadError.unsafeSourceLink(relativePath(from: sourceURL, to: fileURL))
        }

        let rel = relativePath(from: sourceURL, to: fileURL)
        let size = UInt64(values.fileSize ?? 0)
        files.append(SourceFile(
            url: fileURL,
            relativePath: rel,
            size: size,
            modifiedAt: values.contentModificationDate ?? Date(timeIntervalSince1970: 0)
        ))
    }

    return files.sorted { $0.relativePath.localizedStandardCompare($1.relativePath) == .orderedAscending }
}

func relativePath(from root: URL, to file: URL) -> String {
    let rootPath = root.standardizedFileURL.path
    let filePath = file.standardizedFileURL.path
    if filePath == rootPath {
        return file.lastPathComponent
    }
    let prefix = rootPath.hasSuffix("/") ? rootPath : "\(rootPath)/"
    if filePath.hasPrefix(prefix) {
        return String(filePath.dropFirst(prefix.count))
    }
    return file.lastPathComponent
}

func isSameOrNested(_ child: URL, under parent: URL) -> Bool {
    let childPath = child.standardizedFileURL.path
    let parentPath = parent.standardizedFileURL.path
    if childPath == parentPath {
        return true
    }
    let prefix = parentPath.hasSuffix("/") ? parentPath : "\(parentPath)/"
    return childPath.hasPrefix(prefix)
}

func availableCapacity(at url: URL) -> UInt64 {
    let keys: Set<URLResourceKey> = [
        .volumeAvailableCapacityForImportantUsageKey,
        .volumeAvailableCapacityKey
    ]
    if let values = try? url.resourceValues(forKeys: keys) {
        if let important = values.volumeAvailableCapacityForImportantUsage, important > 0 {
            return UInt64(important)
        }
        if let regular = values.volumeAvailableCapacity, regular > 0 {
            return UInt64(regular)
        }
    }
    return 0
}
